import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Serif, Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/dropzone/styles.css';
import Providers from "@/components/providers";

const ibmSans = IBM_Plex_Sans({
  subsets: ["latin"], weight: ["100", "200", "300", "500", "700"],
  display: "swap",
  variable: '--font-main',
  adjustFontFallback: false
})

const ibmSerif = IBM_Plex_Serif({
  subsets: ["latin"], weight: ["100", "200", "300", "500", "700"],
  display: "swap",
  variable: '--font-heading',
  adjustFontFallback: false
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmSans.variable} ${ibmSerif.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
